
project_id = "kvunnankqgfokeufvsrv"

[functions.onet-proxy]
verify_jwt = false

[functions.calculate-apo]
verify_jwt = false

[functions.serpapi-jobs]
verify_jwt = false

[functions.search-occupations]
verify_jwt = false
