export type SourceIntegrationStatus = 'active' | 'adapter-ready' | 'llm-output';
export type SourceConfidence = 'high' | 'medium' | 'low';

export interface SourceManifestEntry {
  id: string;
  label: string;
  provider: string;
  currentVersion: string;
  releaseDate: string;
  lastVerifiedAt: string;
  integrationStatus: SourceIntegrationStatus;
  confidence: SourceConfidence;
  refreshCadence: string;
  usedFor: string;
  caveat: string;
  claimBoundary: string;
  url: string;
}

export interface SourceManifestSnapshotEntry {
  label: string;
  provider: string;
  currentVersion: string;
  releaseDate: string;
  lastVerifiedAt: string;
  integrationStatus: SourceIntegrationStatus;
  confidence: SourceConfidence;
}

export const SOURCE_MANIFEST_LAST_VERIFIED_AT = '2026-05-24';

export const SOURCE_REFRESH_MANIFEST: SourceManifestEntry[] = [
  {
    id: 'onet',
    label: 'O*NET occupational and task data',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 production release',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Quarterly O*NET database release review, then app ingestion verification.',
    usedFor: 'SOC occupation metadata, work activities, task statements, Task Ratings importance/frequency fields, and skill descriptors.',
    caveat: 'O*NET describes occupations, not individual people, employer-specific job design, or exact task-time allocation.',
    claimBoundary: 'Do not claim every in-app row is 30.3-backed until the app data-refresh job and checksum manifest are run.',
    url: 'https://www.onetcenter.org/db_releases.html',
  },
  {
    id: 'onet-task-statements',
    label: 'O*NET 30.3 Task Statements',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before task ingest.',
    usedFor: 'Task statement text, task IDs, occupation linkage, and task type values for onet_detailed_tasks.',
    caveat: 'Task statements describe representative occupation tasks, not employer-specific job design.',
    claimBoundary: 'Do not claim specific worker task inventory without employer/person review.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/task_statements.html',
  },
  {
    id: 'onet-task-ratings',
    label: 'O*NET 30.3 Task Ratings',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before task-weighting changes.',
    usedFor: 'Importance, relevance, frequency, sample size, confidence interval, suppress flag, and domain-source metadata for task weighting.',
    caveat: 'Task ratings are occupation-level survey summaries, not exact task-time allocation for a worker or employer.',
    claimBoundary: 'Do not claim task-time precision until ingested table checksums and report artifact source snapshots prove the ratings were used.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/task_ratings.html',
  },
  {
    id: 'onet-task-categories',
    label: 'O*NET 30.3 Task Categories',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before frequency-label mapping changes.',
    usedFor: 'Human-readable labels for task frequency categories used in task-rating import.',
    caveat: 'Frequency categories are categorical survey summaries and should not be converted directly into task-time percentages.',
    claimBoundary: 'Use frequency labels as prioritization context only unless validated with employer task mix.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/task_categories.html',
  },
  {
    id: 'onet-scales-reference',
    label: 'O*NET 30.3 Scales Reference',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before scale interpretation changes.',
    usedFor: 'Scale definitions for task importance, relevance, and frequency values.',
    caveat: 'Scale definitions support interpretation; they are not a separate labor-market signal.',
    claimBoundary: 'Do not use scale metadata alone as evidence of automation exposure.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/scales_reference.html',
  },
  {
    id: 'bls-emp',
    label: 'BLS Employment Projections',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: '2024-34 occupational employment projections',
    releaseDate: '2025 release cycle',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Annual BLS projections release review.',
    usedFor: 'Employment outlook, growth context, and labor-market baseline signals.',
    caveat: 'BLS projections are macro-level estimates and should not be interpreted as employer-specific forecasts.',
    claimBoundary: 'Use as directional labor-market context, not as a prediction for any single worker or employer.',
    url: 'https://www.bls.gov/emp/',
  },
  {
    id: 'bls-oews',
    label: 'BLS Occupational Employment and Wage Statistics',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: 'May 2025 OEWS tables',
    releaseDate: 'Published May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Annual OEWS table release review.',
    usedFor: 'Wage estimates, occupational employment levels, and location/industry wage context.',
    caveat: 'OEWS wage estimates are survey-based and may exclude bonuses, equity, overtime, or employer-specific compensation design.',
    claimBoundary: 'Use for wage/employment context only after the occupation/SOC mapping has been verified.',
    url: 'https://www.bls.gov/oes/tables.htm',
  },
  {
    id: 'bls-laus',
    label: 'BLS Local Area Unemployment Statistics',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: 'Monthly and annual LAUS data tables and maps',
    releaseDate: 'Monthly release cycle reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Verify with each local labor-market appendix release and before region-specific unemployment context is shown.',
    usedFor: 'State, county, city, and metropolitan labor-force and unemployment context once a geography and month are attached.',
    caveat: 'LAUS is area labor-force context by place of residence; it is not occupation-level demand, hiring, or job-opening evidence.',
    claimBoundary: 'Use only as local labor-market context and never as proof that an occupation is growing or shrinking in a selected region.',
    url: 'https://www.bls.gov/lau/data-overview.htm',
  },
  {
    id: 'bls-qcew',
    label: 'BLS Quarterly Census of Employment and Wages',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: 'QCEW downloadable files and open data access',
    releaseDate: 'Current public data portal reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Verify quarterly before industry/geography employment context is attached to workforce proof packs.',
    usedFor: 'County, state, industry, establishment, employment, and wage context for workforce-board and L&D pilots.',
    caveat: 'QCEW is industry/geography context, not detailed occupation, skill, role-title, or posting demand evidence.',
    claimBoundary: 'Use alongside OEWS, postings, or employer data for occupation-level claims; do not treat QCEW alone as skill demand proof.',
    url: 'https://www.bls.gov/cew/data-overview.htm',
  },
  {
    id: 'careeronestop-api',
    label: 'CareerOneStop Web API Services',
    provider: 'CareerOneStop, sponsored by the U.S. Department of Labor Employment and Training Administration',
    currentVersion: 'Authenticated REST API catalog',
    releaseDate: 'Current public API explorer reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Verify endpoint catalog and authentication requirements before occupation, salary, LMI, training, or skills-gap calls are enabled.',
    usedFor: 'Authenticated occupation, salary, labor-market information, training, licensing, skills-gap, and local workforce-service cross-checks.',
    caveat: 'CareerOneStop API calls require authenticated access and per-query source logging; API availability does not validate any provider, course, or outcome.',
    claimBoundary: 'Use as a cross-check adapter only until endpoint, token owner, query, location, timestamp, and reviewer notes are stored per artifact.',
    url: 'https://github.com/CareerOneStop/API-Overview',
  },
  {
    id: 'census-acs-api',
    label: 'Census American Community Survey Data API',
    provider: 'U.S. Census Bureau',
    currentVersion: 'ACS API with 2005-2024 1-year data listed',
    releaseDate: 'Current ACS API catalog reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Verify ACS vintage, geography, variables, and margin-of-error handling before demographic or access-context appendix rows are generated.',
    usedFor: 'Local demographic, education, commuting, language, broadband, income, and access-context variables for workforce planning caveats.',
    caveat: 'ACS is contextual population and community data, not occupation-specific demand or individual suitability evidence.',
    claimBoundary: 'Use only for contextual planning; never use demographic variables to rank, screen, or make employment decisions about people.',
    url: 'https://www.census.gov/programs-surveys/acs/data/data-via-api.html',
  },
  {
    id: 'wef-foj-2025',
    label: 'Future of Jobs Report 2025',
    provider: 'World Economic Forum',
    currentVersion: '2025 edition',
    releaseDate: 'Published January 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Report-cycle review plus annual narrative check for newer WEF future-of-work reports.',
    usedFor: 'Macro technology, skill demand, and workforce-transition framing over the 2025-2030 horizon.',
    caveat: 'WEF signals are directional employer-survey insights and should be combined with occupation-level data.',
    claimBoundary: 'Use for macro narrative and skill trend framing, not for occupation-level scoring on its own.',
    url: 'https://www.weforum.org/publications/the-future-of-jobs-report-2025/',
  },
  {
    id: 'oecd-skills-outlook-2025',
    label: 'OECD Skills Outlook 2025',
    provider: 'Organisation for Economic Co-operation and Development',
    currentVersion: '2025 edition',
    releaseDate: 'Published 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review each OECD Skills Outlook or AI-and-skills release before changing skill-transition claims.',
    usedFor: 'Skill-change framing, task-content change, and reskilling-policy context for labour-market transitions.',
    caveat: 'OECD evidence is cross-country and policy-oriented; it does not validate a specific worker, employer, or local posting market.',
    claimBoundary: 'Use to justify skill-change categories and caveats, not as standalone occupation scoring.',
    url: 'https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/12/oecd-skills-outlook-2025_ac37c7d4/26163cd3-en.pdf',
  },
  {
    id: 'ai-workforce-consortium-2025',
    label: 'AI Workforce Consortium ICT in Motion 2025',
    provider: 'AI Workforce Consortium, led by Cisco',
    currentVersion: '2025 ICT in Motion report',
    releaseDate: 'Published September 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review when the Consortium publishes new AI workforce, skills, or role-transition reports.',
    usedFor: 'AI-era role radar market-signal framing, especially AI-specific and specialized support-role language.',
    caveat: 'The report focuses on G7 ICT and specialized support roles from selected job-posting sources; it does not validate every region, employer, or role title.',
    claimBoundary: 'Use as emerging-role and AI-skill signal context only; do not treat as title-level proof without posting, taxonomy, or employer validation.',
    url: 'https://newsroom.cisco.com/c/r/newsroom/en/us/a/y2025/m09/ai-workforce-consortium-finds-78-of-ict-roles-now-include-ai-technical-skills-while-human-skills-gain-priority-for-responsible-tech-adoption.html',
  },
  {
    id: 'nace-career-readiness',
    label: 'NACE Career Readiness Competencies',
    provider: 'National Association of Colleges and Employers',
    currentVersion: 'Career readiness competency framework current public page',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing career-center, coach, or student-facing outreach claims.',
    usedFor: 'Career-center and coach outreach framing, transferable-skill language, and student/alumni development context.',
    caveat: 'NACE competency language is a career-readiness framework, not an AI exposure model or labor-market demand dataset.',
    claimBoundary: 'Use to frame buyer workflows and development conversations; do not imply NACE validates the product, scores, or recommendations.',
    url: 'https://www.naceweb.org/career-readiness/competencies/career-readiness-defined',
  },
  {
    id: 'nace-first-destination',
    label: 'NACE First-Destination Standards and Protocols',
    provider: 'National Association of Colleges and Employers',
    currentVersion: 'First-destination standards and protocols public page',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Review before adding outcome, salary, placement, or graduate-outcome claims to cohort proof packs.',
    usedFor: 'Career-center outcome-reporting boundary language and separation of proof-pack transition guidance from first-destination outcomes.',
    caveat: 'First-destination standards describe career-outcome reporting practices; they do not validate transition recommendations or individual student outcomes.',
    claimBoundary: 'Do not call a cohort proof pack a placement, salary, or career-outcome report unless institution-approved outcome evidence is separately collected and reviewed.',
    url: 'https://www.naceweb.org/job-market/graduate-outcomes/first-destination/standards-and-protocols/',
  },
  {
    id: 'ferpa-student-privacy',
    label: 'FERPA student privacy guidance',
    provider: 'U.S. Department of Education Student Privacy Policy Office',
    currentVersion: 'Student records and privacy FAQ plus PII guidance',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Review before student, alumni, cohort, roster, or education-record data is stored or exported.',
    usedFor: 'Aggregate-only cohort reporting boundaries, personally identifiable education-record caveats, and advisor-review requirements.',
    caveat: 'FERPA guidance is not legal advice and does not certify any product workflow or institutional data-sharing process.',
    claimBoundary: 'Do not store or export student PII in cohort proof packs unless the institution has approved consent, legitimate-interest, disclosure, retention, and access controls.',
    url: 'https://studentprivacy.ed.gov/content/personally-identifiable-information-education-records',
  },
  {
    id: 'dol-ai-literacy-framework',
    label: 'DOL AI Literacy Framework',
    provider: 'U.S. Department of Labor Employment and Training Administration',
    currentVersion: 'Training and Employment Notice No. 07-25',
    releaseDate: 'Published February 13, 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing AI-literacy, workforce-board, or training-provider outreach claims.',
    usedFor: 'AI literacy, workforce-board, training-provider, and L&D pilot framing for role-specific AI skill development.',
    caveat: 'The framework is guidance for AI literacy program design and does not validate a specific worker, employer, course, or assessment.',
    claimBoundary: 'Use as workforce and education context only; do not claim DOL endorsement, grant eligibility, or employment-outcome proof.',
    url: 'https://www.dol.gov/agencies/eta/advisories/ten-07-25',
  },
  {
    id: 'anthropic-economic-index',
    label: 'Anthropic Economic Index',
    provider: 'Anthropic',
    currentVersion: 'Initial Economic Index plus 2026 Economic Primitives updates',
    releaseDate: 'February 2025 and 2026 updates',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review each public Economic Index release and open dataset update before refreshing AI-use claims.',
    usedFor: 'Observed AI use by O*NET task, automation versus augmentation framing, and adoption-inequality caveats.',
    caveat: 'Claude usage is not representative of all AI use, all workers, or all countries, and the source describes observed usage rather than complete automation feasibility.',
    claimBoundary: 'Use as an external AI-use benchmark and caveat layer; do not treat it as the app scoring source until imported task-level datasets are versioned and validated.',
    url: 'https://www.anthropic.com/research/the-anthropic-economic-index',
  },
  {
    id: 'anthropic-observed-exposure',
    label: 'Anthropic observed AI exposure research',
    provider: 'Anthropic',
    currentVersion: 'Labor market impacts observed-exposure research',
    releaseDate: '2026 research release',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review when Anthropic publishes new Economic Index labor-market datasets or methodology updates.',
    usedFor: 'Distinguishing theoretical task capability from observed automated, work-related AI use.',
    caveat: 'Observed exposure is based on Claude usage and external task-exposure estimates; it is not a complete labor-market outcome measure.',
    claimBoundary: 'Use to explain why task capability, observed AI use, hiring, and displacement must be separated in commercial reports.',
    url: 'https://www.anthropic.com/research/labor-market-impacts',
  },
  {
    id: 'openai-gdpval',
    label: 'OpenAI GDPval occupational task evaluation',
    provider: 'OpenAI',
    currentVersion: 'GDPval first version',
    releaseDate: 'Published September 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review new GDPval releases and gold-set updates before making capability benchmark claims.',
    usedFor: 'AI capability benchmark framing for economically valuable knowledge-work tasks.',
    caveat: 'GDPval is an evaluation benchmark, not a labor-market forecast, and its first version covers a limited set of knowledge-work occupations.',
    claimBoundary: 'Use for capability trend context only; do not translate benchmark performance directly into job-loss or hiring predictions.',
    url: 'https://arxiv.org/abs/2510.04374',
  },
  {
    id: 'bls-ai-mlr-2025',
    label: 'BLS AI impacts in employment projections',
    provider: 'U.S. Bureau of Labor Statistics Monthly Labor Review',
    currentVersion: '2025 occupational case-study article',
    releaseDate: 'Published February 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review each annual BLS projections cycle and related AI/technology Monthly Labor Review updates.',
    usedFor: 'Claim discipline around AI exposure, employment projections uncertainty, and occupation-specific counterexamples.',
    caveat: 'BLS emphasizes that technology impacts can be gradual and uncertain; exposure does not imply rapid displacement.',
    claimBoundary: 'Use to temper automation claims and explain uncertainty, not as a direct replacement for app scoring or employer-specific forecasts.',
    url: 'https://www.bls.gov/opub/mlr/2025/article/incorporating-ai-impacts-in-bls-employment-projections.htm',
  },
  {
    id: 'wcag-22',
    label: 'WCAG 2.2 accessibility standard',
    provider: 'World Wide Web Consortium',
    currentVersion: 'WCAG 2.2 Recommendation',
    releaseDate: 'December 2024 update',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review when commercial routes are changed and before institutional demos.',
    usedFor: 'Accessibility conformance target for public report, lead-capture, coach, and workforce pilot surfaces.',
    caveat: 'Automated checks cannot prove full WCAG conformance; manual keyboard, screen-reader, contrast, focus, and error-state review are still required.',
    claimBoundary: 'Do not claim WCAG conformance until the audit checklist, remediation evidence, and manual test notes are complete.',
    url: 'https://www.w3.org/TR/WCAG22/',
  },
  {
    id: 'nist-ai-rmf',
    label: 'NIST AI Risk Management Framework',
    provider: 'U.S. National Institute of Standards and Technology',
    currentVersion: 'AI RMF 1.0',
    releaseDate: 'January 2023; current framework reviewed in 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing report governance, review-state, or risk-note language.',
    usedFor: 'Risk notes, human-review states, governance boundaries, and trustworthy AI framing.',
    caveat: 'The AI RMF is a voluntary risk-management framework and does not itself validate a product for employment decisions.',
    claimBoundary: 'Use as a governance scaffold only; do not claim certification, compliance, or formal validation from referencing it.',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
  },
  {
    id: 'owasp-file-upload',
    label: 'OWASP File Upload Cheat Sheet',
    provider: 'OWASP Cheat Sheet Series',
    currentVersion: 'Current public file-upload guidance',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing resume upload, file validation, parser, or storage behavior.',
    usedFor: 'Resume upload boundary controls: extension allowlist, content-type caveat, file-signature checks, size limits, storage minimization, and malware-scan caveats.',
    caveat: 'OWASP guidance informs secure upload handling, but it does not prove any uploaded file is safe, malware-free, or parsed completely.',
    claimBoundary: 'Do not enable paid PDF/DOCX upload workflows until server-side validation, parser behavior, deletion receipts, and unresolved malware-scan limitations are visible in the proof packet.',
    url: 'https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html',
  },
  {
    id: 'supabase-edge-functions',
    label: 'Supabase Edge Functions',
    provider: 'Supabase',
    currentVersion: 'Current Edge Functions platform documentation',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing Edge Function parser, upload, runtime-limit, or deployment assumptions.',
    usedFor: 'Server-side parser boundary, multipart upload handling, runtime limits, auth/header validation, and deployment runbook caveats.',
    caveat: 'Edge Functions are suitable for short validation and orchestration; heavy parsing, antivirus scanning, or large-file processing may need a dedicated service or background worker.',
    claimBoundary: 'Do not claim production PDF/DOCX parser readiness until the deployed function, file-size limits, parser adapter, deletion proof, and error-path artifacts pass verification.',
    url: 'https://supabase.com/docs/guides/functions',
  },
  {
    id: 'ada-ai-hiring-guidance',
    label: 'ADA algorithmic hiring guidance',
    provider: 'U.S. Department of Justice and EEOC',
    currentVersion: 'Algorithms, Artificial Intelligence, and Disability Discrimination in Hiring guidance',
    releaseDate: 'Guidance current as of 2026 review',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before any employer-facing workflow could influence selection, promotion, or workforce decisions.',
    usedFor: 'Employment-decision disclaimers, accommodation language, and human-review guardrails.',
    caveat: 'This guidance is not a substitute for legal advice and does not make the product validated for selection procedures.',
    claimBoundary: 'Use reports for planning and discussion only unless a formal validation, accommodation, and adverse-impact review program exists.',
    url: 'https://www.ada.gov/resources/ai-guidance/',
  },
  {
    id: 'eeoc-employment-selection-procedures',
    label: 'EEOC employment tests and selection procedures',
    provider: 'U.S. Equal Employment Opportunity Commission',
    currentVersion: 'Employment Tests and Selection Procedures technical assistance',
    releaseDate: 'December 1, 2007; current page reviewed in 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before any employer-facing workflow could influence selection, promotion, or workforce decisions.',
    usedFor: 'Employment-selection overclaim boundaries, adverse-impact caveats, and proof that report outputs are planning artifacts unless formally validated.',
    caveat: 'This technical assistance is not legal advice and does not validate this product as an employment selection procedure.',
    claimBoundary: 'Do not use proof-pack scores for hiring, firing, promotion, compensation, retention, screening, or eligibility decisions without a formal validated employment-selection program.',
    url: 'https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures',
  },
  {
    id: 'cfpb-employment-algorithmic-scores',
    label: 'CFPB employment algorithmic score circular',
    provider: 'Consumer Financial Protection Bureau',
    currentVersion: 'Consumer Financial Protection Circular 2024-06',
    releaseDate: 'October 24, 2024; Federal Register publication November 12, 2024',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before any report, score, or worker dossier is shared with an employer or third party.',
    usedFor: 'Consumer-report and employment-purpose overclaim boundaries for individual resume and worker-score artifacts.',
    caveat: 'This circular does not make the product a consumer reporting agency by itself, but it flags FCRA risk if third-party reports or scores are used for employment purposes.',
    claimBoundary: 'Do not furnish individual proof-pack reports to employers for employment purposes unless FCRA, notice, dispute, permission, accuracy, and legal review controls are implemented.',
    url: 'https://www.consumerfinance.gov/compliance/circulars/consumer-financial-protection-circular-2024-06-background-dossiers-and-algorithmic-scores-for-hiring-promotion-and-other-employment-decisions/',
  },
  {
    id: 'iso-42001',
    label: 'ISO/IEC 42001 AI management system',
    provider: 'International Organization for Standardization',
    currentVersion: 'ISO/IEC 42001:2023',
    releaseDate: 'Published December 2023',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing AI governance, review attestation, or buyer trust claims.',
    usedFor: 'AI governance, traceability, transparency, and review-attestation framing for institutional proof-pack delivery.',
    caveat: 'Referencing ISO/IEC 42001 does not certify this product or any customer AI management system.',
    claimBoundary: 'Use as governance design context only; do not claim ISO certification or compliance from source labeling alone.',
    url: 'https://www.iso.org/standard/42001',
  },
  {
    id: 'esco',
    label: 'ESCO skills and occupation taxonomy',
    provider: 'European Commission',
    currentVersion: 'ESCO v1.2.1',
    releaseDate: 'Last update 2025-12-10',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Monitor ESCO release notes before international skill mapping claims.',
    usedFor: 'International skill language, multilingual skills, and non-U.S. occupation alignment.',
    caveat: 'Requires mapping to local SOC/O*NET rows before it can power scored U.S. reports.',
    claimBoundary: 'Adapter boundary only until the ESCO import, crosswalk, and validation checks exist in this repo.',
    url: 'https://esco.ec.europa.eu/en/use-esco/use-esco-services-api',
  },
  {
    id: 'lightcast',
    label: 'Lightcast skills and labor-market data',
    provider: 'Lightcast',
    currentVersion: 'Commercial adapter boundary',
    releaseDate: 'Not licensed in this repository',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Review only after commercial data agreement and adapter credentials exist.',
    usedFor: 'Job-posting demand, emerging skills, and employer language once licensed.',
    caveat: 'Not bundled in this repository; production use requires a licensed data agreement and ingestion adapter.',
    claimBoundary: 'Do not imply Lightcast-backed scoring until a licensed adapter and provenance log are implemented.',
    url: 'https://lightcast.io/',
  },
  {
    id: 'workera-positioning',
    label: 'Workera skills intelligence positioning',
    provider: 'Workera',
    currentVersion: 'Public product overview',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Review during competitive-positioning refreshes before changing skills-intelligence claims.',
    usedFor: 'Competitive landscape context around verified skills, defensible evidence, and enterprise buyer expectations.',
    caveat: 'Public competitor positioning is not a data feed, benchmark, or endorsement.',
    claimBoundary: 'Use only for market-positioning context; do not imply Workera-backed validation, integration, or comparable assessment depth.',
    url: 'https://www.workera.ai/product-overview',
  },
  {
    id: 'serpapi',
    label: 'Live market search signals',
    provider: 'SerpAPI-compatible search adapter',
    currentVersion: 'Adapter boundary',
    releaseDate: 'Runtime query timestamp required',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Per-query timestamp, cache key, and jurisdiction capture required.',
    usedFor: 'Current SERP/job-market snapshots for outreach and content validation.',
    caveat: 'Search results are volatile and must be cached with query, timestamp, and jurisdiction.',
    claimBoundary: 'Use only as freshness context until a query log, cache policy, and result-review workflow are implemented.',
    url: 'https://serpapi.com/',
  },
  {
    id: 'llm-output',
    label: 'LLM-generated analysis',
    provider: 'Configured AI model or Supabase Edge Function',
    currentVersion: 'Runtime configured model',
    releaseDate: 'Runtime model/version metadata required',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'llm-output',
    confidence: 'low',
    refreshCadence: 'Capture model name, prompt version, and generation timestamp per artifact.',
    usedFor: 'Narrative explanations, resume rewrites, caveat summaries, and draft recommendations.',
    caveat: 'LLM output is advisory. It needs source grounding, human review, and should never be the sole basis for employment decisions.',
    claimBoundary: 'Treat as draft narrative unless grounded source IDs, human review state, and prompt/model metadata are attached.',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
  },
];

export function getSourceManifestSnapshot(): Record<string, SourceManifestSnapshotEntry> {
  return SOURCE_REFRESH_MANIFEST.reduce<Record<string, SourceManifestSnapshotEntry>>((acc, source) => {
    acc[source.id] = {
      label: source.label,
      provider: source.provider,
      currentVersion: source.currentVersion,
      releaseDate: source.releaseDate,
      lastVerifiedAt: source.lastVerifiedAt,
      integrationStatus: source.integrationStatus,
      confidence: source.confidence,
    };
    return acc;
  }, {});
}

export function getActiveSourceVersionSummary(): string {
  return SOURCE_REFRESH_MANIFEST.filter((source) => source.integrationStatus === 'active')
    .map((source) => `${source.label}: ${source.currentVersion} (${source.releaseDate})`)
    .join('; ');
}
