export type SourceIntegrationStatus = 'active' | 'adapter-ready' | 'llm-output';
export type SourceConfidence = 'high' | 'medium' | 'low';

export interface SourceManifestEntry {
  id: string;
  label: string;
  provider: string;
  currentVersion: string;
  releaseDate: string;
  lastVerifiedAt: string;
  integrationStatus: SourceIntegrationStatus;
  confidence: SourceConfidence;
  refreshCadence: string;
  usedFor: string;
  caveat: string;
  claimBoundary: string;
  url: string;
}

export interface SourceManifestSnapshotEntry {
  label: string;
  provider: string;
  currentVersion: string;
  releaseDate: string;
  lastVerifiedAt: string;
  integrationStatus: SourceIntegrationStatus;
  confidence: SourceConfidence;
}

export const SOURCE_MANIFEST_LAST_VERIFIED_AT = '2026-06-08';

export const SOURCE_REFRESH_MANIFEST: SourceManifestEntry[] = [
  {
    id: 'onet',
    label: 'O*NET occupational and task data',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 production release',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Quarterly O*NET database release review, then app ingestion verification.',
    usedFor: 'SOC occupation metadata, work activities, task statements, Task Ratings importance/frequency fields, and skill descriptors.',
    caveat: 'O*NET describes occupations, not individual people, employer-specific job design, or exact task-time allocation.',
    claimBoundary: 'Do not claim every in-app row is 30.3-backed until the app data-refresh job and checksum manifest are run.',
    url: 'https://www.onetcenter.org/db_releases.html',
  },
  {
    id: 'onet-task-statements',
    label: 'O*NET 30.3 Task Statements',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before task ingest.',
    usedFor: 'Task statement text, task IDs, occupation linkage, and task type values for onet_detailed_tasks.',
    caveat: 'Task statements describe representative occupation tasks, not employer-specific job design.',
    claimBoundary: 'Do not claim specific worker task inventory without employer/person review.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/task_statements.html',
  },
  {
    id: 'onet-task-ratings',
    label: 'O*NET 30.3 Task Ratings',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before task-weighting changes.',
    usedFor: 'Importance, relevance, frequency, sample size, confidence interval, suppress flag, and domain-source metadata for task weighting.',
    caveat: 'Task ratings are occupation-level survey summaries, not exact task-time allocation for a worker or employer.',
    claimBoundary: 'Do not claim task-time precision until ingested table checksums and report artifact source snapshots prove the ratings were used.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/task_ratings.html',
  },
  {
    id: 'onet-task-categories',
    label: 'O*NET 30.3 Task Categories',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before frequency-label mapping changes.',
    usedFor: 'Human-readable labels for task frequency categories used in task-rating import.',
    caveat: 'Frequency categories are categorical survey summaries and should not be converted directly into task-time percentages.',
    claimBoundary: 'Use frequency labels as prioritization context only unless validated with employer task mix.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/task_categories.html',
  },
  {
    id: 'onet-scales-reference',
    label: 'O*NET 30.3 Scales Reference',
    provider: 'U.S. Department of Labor, O*NET Resource Center',
    currentVersion: 'O*NET Database 30.3 text dictionary',
    releaseDate: 'May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Verify with each O*NET release before scale interpretation changes.',
    usedFor: 'Scale definitions for task importance, relevance, and frequency values.',
    caveat: 'Scale definitions support interpretation; they are not a separate labor-market signal.',
    claimBoundary: 'Do not use scale metadata alone as evidence of automation exposure.',
    url: 'https://www.onetcenter.org/dictionary/30.3/text/scales_reference.html',
  },
  {
    id: 'bls-emp',
    label: 'BLS Employment Projections',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: '2024-34 occupational employment projections',
    releaseDate: '2025 release cycle',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Annual BLS projections release review.',
    usedFor: 'Employment outlook, growth context, and labor-market baseline signals.',
    caveat: 'BLS projections are macro-level estimates and should not be interpreted as employer-specific forecasts.',
    claimBoundary: 'Use as directional labor-market context, not as a prediction for any single worker or employer.',
    url: 'https://www.bls.gov/emp/',
  },
  {
    id: 'bls-oews',
    label: 'BLS Occupational Employment and Wage Statistics',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: 'May 2025 OEWS tables',
    releaseDate: 'Published May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Annual OEWS table release review.',
    usedFor: 'Wage estimates, occupational employment levels, and location/industry wage context.',
    caveat: 'OEWS wage estimates are survey-based and may exclude bonuses, equity, overtime, or employer-specific compensation design.',
    claimBoundary: 'Use for wage/employment context only after the occupation/SOC mapping has been verified.',
    url: 'https://www.bls.gov/oes/tables.htm',
  },
  {
    id: 'bls-laus',
    label: 'BLS Local Area Unemployment Statistics',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: 'Monthly and annual LAUS data tables and maps',
    releaseDate: 'Monthly release cycle reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Verify with each local labor-market appendix release and before region-specific unemployment context is shown.',
    usedFor: 'State, county, city, and metropolitan labor-force and unemployment context once a geography and month are attached.',
    caveat: 'LAUS is area labor-force context by place of residence; it is not occupation-level demand, hiring, or job-opening evidence.',
    claimBoundary: 'Use only as local labor-market context and never as proof that an occupation is growing or shrinking in a selected region.',
    url: 'https://www.bls.gov/lau/data-overview.htm',
  },
  {
    id: 'bls-qcew',
    label: 'BLS Quarterly Census of Employment and Wages',
    provider: 'U.S. Bureau of Labor Statistics',
    currentVersion: 'QCEW downloadable files and open data access',
    releaseDate: 'Current public data portal reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Verify quarterly before industry/geography employment context is attached to workforce proof packs.',
    usedFor: 'County, state, industry, establishment, employment, and wage context for workforce-board and L&D pilots.',
    caveat: 'QCEW is industry/geography context, not detailed occupation, skill, role-title, or posting demand evidence.',
    claimBoundary: 'Use alongside OEWS, postings, or employer data for occupation-level claims; do not treat QCEW alone as skill demand proof.',
    url: 'https://www.bls.gov/cew/data-overview.htm',
  },
  {
    id: 'careeronestop-api',
    label: 'CareerOneStop Web API Services',
    provider: 'CareerOneStop, sponsored by the U.S. Department of Labor Employment and Training Administration',
    currentVersion: 'Authenticated REST API catalog',
    releaseDate: 'Current public API explorer reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Verify endpoint catalog and authentication requirements before occupation, salary, LMI, training, or skills-gap calls are enabled.',
    usedFor: 'Authenticated occupation, salary, labor-market information, training, licensing, skills-gap, and local workforce-service cross-checks.',
    caveat: 'CareerOneStop API calls require authenticated access and per-query source logging; API availability does not validate any provider, course, or outcome.',
    claimBoundary: 'Use as a cross-check adapter only until endpoint, token owner, query, location, timestamp, and reviewer notes are stored per artifact.',
    url: 'https://github.com/CareerOneStop/API-Overview',
  },
  {
    id: 'census-acs-api',
    label: 'Census American Community Survey Data API',
    provider: 'U.S. Census Bureau',
    currentVersion: 'ACS API with 2005-2024 1-year data listed',
    releaseDate: 'Current ACS API catalog reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Verify ACS vintage, geography, variables, and margin-of-error handling before demographic or access-context appendix rows are generated.',
    usedFor: 'Local demographic, education, commuting, language, broadband, income, and access-context variables for workforce planning caveats.',
    caveat: 'ACS is contextual population and community data, not occupation-specific demand or individual suitability evidence.',
    claimBoundary: 'Use only for contextual planning; never use demographic variables to rank, screen, or make employment decisions about people.',
    url: 'https://www.census.gov/programs-surveys/acs/data/data-via-api.html',
  },
  {
    id: 'wef-foj-2025',
    label: 'Future of Jobs Report 2025',
    provider: 'World Economic Forum',
    currentVersion: '2025 edition',
    releaseDate: 'Published January 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Report-cycle review plus annual narrative check for newer WEF future-of-work reports.',
    usedFor: 'Macro technology, skill demand, and workforce-transition framing over the 2025-2030 horizon.',
    caveat: 'WEF signals are directional employer-survey insights and should be combined with occupation-level data.',
    claimBoundary: 'Use for macro narrative and skill trend framing, not for occupation-level scoring on its own.',
    url: 'https://www.weforum.org/publications/the-future-of-jobs-report-2025/',
  },
  {
    id: 'ilo-genai-jobs-2025',
    label: 'Generative AI and jobs: A 2025 update',
    provider: 'International Labour Organization and NASK',
    currentVersion: '2025 research brief update',
    releaseDate: 'Published May 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review when ILO publishes GenAI occupation-exposure index updates.',
    usedFor: 'Task-exposure framing, occupation-exposure caveats, and the transformation-not-replacement boundary.',
    caveat: 'The ILO study estimates potential exposure and transformation pressure; it is not a prediction that individual jobs disappear.',
    claimBoundary: 'Use for task-exposure and transformation framing only; do not convert exposure categories into job-loss probabilities.',
    url: 'https://www.ilo.org/publications/generative-ai-and-jobs-2025-update',
  },
  {
    id: 'openai-eloundou-gpts-are-gpts',
    label: 'GPTs are GPTs: labor market impact potential of LLMs',
    provider: 'OpenAI, OpenResearch, and University of Pennsylvania authors',
    currentVersion: 'Science publication / arXiv paper',
    releaseDate: 'Original arXiv 2023; journal publication 2024',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing exposure-language or task-productivity framing.',
    usedFor: 'LLM exposure definition, task-level productivity-exposure language, and worker-level non-prediction caveats.',
    caveat: 'The paper measures exposure potential under assumptions; it does not validate APO scores or forecast employment outcomes.',
    claimBoundary: 'Use to explain exposure methodology; do not claim the app reproduces the paper or predicts displacement.',
    url: 'https://arxiv.org/abs/2303.10130',
  },
  {
    id: 'oecd-skills-outlook-2025',
    label: 'OECD Skills Outlook 2025',
    provider: 'Organisation for Economic Co-operation and Development',
    currentVersion: '2025 edition',
    releaseDate: 'Published 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review each OECD Skills Outlook or AI-and-skills release before changing skill-transition claims.',
    usedFor: 'Skill-change framing, task-content change, and reskilling-policy context for labour-market transitions.',
    caveat: 'OECD evidence is cross-country and policy-oriented; it does not validate a specific worker, employer, or local posting market.',
    claimBoundary: 'Use to justify skill-change categories and caveats, not as standalone occupation scoring.',
    url: 'https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/12/oecd-skills-outlook-2025_ac37c7d4/26163cd3-en.pdf',
  },
  {
    id: 'ai-workforce-consortium-2025',
    label: 'AI Workforce Consortium ICT in Motion 2025',
    provider: 'AI Workforce Consortium, led by Cisco',
    currentVersion: '2025 ICT in Motion report',
    releaseDate: 'Published September 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review when the Consortium publishes new AI workforce, skills, or role-transition reports.',
    usedFor: 'AI-era role radar market-signal framing, especially AI-specific and specialized support-role language.',
    caveat: 'The report focuses on G7 ICT and specialized support roles from selected job-posting sources; it does not validate every region, employer, or role title.',
    claimBoundary: 'Use as emerging-role and AI-skill signal context only; do not treat as title-level proof without posting, taxonomy, or employer validation.',
    url: 'https://newsroom.cisco.com/c/r/newsroom/en/us/a/y2025/m09/ai-workforce-consortium-finds-78-of-ict-roles-now-include-ai-technical-skills-while-human-skills-gain-priority-for-responsible-tech-adoption.html',
  },
  {
    id: 'nace-career-readiness',
    label: 'NACE Career Readiness Competencies',
    provider: 'National Association of Colleges and Employers',
    currentVersion: 'Career readiness competency framework current public page',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing career-center, coach, or student-facing outreach claims.',
    usedFor: 'Career-center and coach outreach framing, transferable-skill language, and student/alumni development context.',
    caveat: 'NACE competency language is a career-readiness framework, not an AI exposure model or labor-market demand dataset.',
    claimBoundary: 'Use to frame buyer workflows and development conversations; do not imply NACE validates the product, scores, or recommendations.',
    url: 'https://www.naceweb.org/career-readiness/competencies/career-readiness-defined',
  },
  {
    id: 'nace-first-destination',
    label: 'NACE First-Destination Standards and Protocols',
    provider: 'National Association of Colleges and Employers',
    currentVersion: 'First-destination standards and protocols public page',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Review before adding outcome, salary, placement, or graduate-outcome claims to cohort proof packs.',
    usedFor: 'Career-center outcome-reporting boundary language and separation of proof-pack transition guidance from first-destination outcomes.',
    caveat: 'First-destination standards describe career-outcome reporting practices; they do not validate transition recommendations or individual student outcomes.',
    claimBoundary: 'Do not call a cohort proof pack a placement, salary, or career-outcome report unless institution-approved outcome evidence is separately collected and reviewed.',
    url: 'https://www.naceweb.org/job-market/graduate-outcomes/first-destination/standards-and-protocols/',
  },
  {
    id: 'ftc-consumer-reviews-rule-questions',
    label: 'FTC Consumer Reviews and Testimonials Rule questions',
    provider: 'Federal Trade Commission',
    currentVersion: 'Consumer Reviews and Testimonials Rule staff Q&A',
    releaseDate: 'Rule effective October 21, 2024; staff Q&A reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing partner-commitment, testimonial, review-solicitation, quote-approval, or case-study evidence language.',
    usedFor: 'Review and testimonial rule awareness, fake/false testimonial boundaries, owner-held partner/outcome quote approval, and commercial-evidence intake caveats.',
    caveat: 'FTC staff guidance is not definitive or comprehensive and does not provide a safe harbor; testimonial duties depend on context and facts.',
    claimBoundary: 'Use as advertising/testimonial integrity context only; do not claim legal compliance, permission to cite, testimonial typicality, outcome substantiation, or FTC endorsement from referencing it.',
    url: 'https://www.ftc.gov/business-guidance/resources/consumer-reviews-testimonials-rule-questions-answers',
  },
  {
    id: 'ftc-endorsements-reviews',
    label: 'FTC Endorsements, Influencers, and Reviews hub',
    provider: 'Federal Trade Commission',
    currentVersion: 'Advertising and Marketing topic hub for endorsements, influencers, and reviews',
    releaseDate: 'Reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing commercial evidence intake sources, testimonial governance, or review-solicitation owner instructions.',
    usedFor: 'Commercial evidence intake source grouping for consumer reviews, endorsements, disclosures, and review-solicitation guidance.',
    caveat: 'FTC topic hubs organize guidance and legal resources but do not review or approve this product, its testimonials, or its marketing evidence.',
    claimBoundary: 'Use as a navigation and governance source only; do not claim FTC compliance, testimonial approval, permission to cite, or outcome substantiation without owner-held legal/evidence review.',
    url: 'https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews',
  },
  {
    id: 'ftc-endorsement-guides-faq',
    label: "FTC Endorsement Guides: What People Are Asking",
    provider: 'Federal Trade Commission',
    currentVersion: '2023 revised Endorsement Guides staff Q&A',
    releaseDate: 'Revised guides released June 2023; staff Q&A reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing material-connection, incentive, testimonial-disclosure, influencer, review, or case-study claim language.',
    usedFor: 'Material-connection disclosure review, incentive caveats, testimonial presentation boundaries, and owner-held commercial validation evidence requirements.',
    caveat: 'FTC endorsement guidance is fact-specific and does not replace legal review of actual testimonials, endorsements, material connections, or incentives.',
    claimBoundary: 'Use as disclosure and endorsement-governance context only; do not claim FTC compliance, testimonial clearance, marketing approval, or generalized customer outcomes without owner-held legal/evidence review.',
    url: 'https://www.ftc.gov/business-guidance/resources/ftcs-endorsement-guides-what-people-are-asking',
  },
  {
    id: 'ftc-soliciting-paying-online-reviews',
    label: 'FTC Soliciting and Paying for Online Reviews guide',
    provider: 'Federal Trade Commission',
    currentVersion: 'Guide for marketers on review solicitation and paid online review risks',
    releaseDate: 'Reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing partner/outcome review-solicitation, incentive, reputation-management, or case-study owner instructions.',
    usedFor: 'Owner-held commercial evidence intake boundaries for review solicitation, incentives, fake-review avoidance, and independent-review caveats.',
    caveat: 'FTC staff business guidance is context-specific and does not substitute for legal review of actual partner commitments, reviews, endorsements, or outcome claims.',
    claimBoundary: 'Use as review-solicitation integrity context only; do not claim lawful marketing use, review authenticity, testimonial typicality, customer outcomes, or FTC approval from referencing it.',
    url: 'https://www.ftc.gov/business-guidance/resources/soliciting-paying-online-reviews-guide-marketers',
  },
  {
    id: 'ferpa-student-privacy',
    label: 'FERPA student privacy guidance',
    provider: 'U.S. Department of Education Student Privacy Policy Office',
    currentVersion: 'Student records and privacy FAQ plus PII guidance',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Review before student, alumni, cohort, roster, or education-record data is stored or exported.',
    usedFor: 'Aggregate-only cohort reporting boundaries, personally identifiable education-record caveats, and advisor-review requirements.',
    caveat: 'FERPA guidance is not legal advice and does not certify any product workflow or institutional data-sharing process.',
    claimBoundary: 'Do not store or export student PII in cohort proof packs unless the institution has approved consent, legitimate-interest, disclosure, retention, and access controls.',
    url: 'https://studentprivacy.ed.gov/content/personally-identifiable-information-education-records',
  },
  {
    id: 'dol-ai-literacy-framework',
    label: 'DOL AI Literacy Framework',
    provider: 'U.S. Department of Labor Employment and Training Administration',
    currentVersion: 'Training and Employment Notice No. 07-25',
    releaseDate: 'Published February 13, 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing AI-literacy, workforce-board, or training-provider outreach claims.',
    usedFor: 'AI literacy, workforce-board, training-provider, and L&D pilot framing for role-specific AI skill development.',
    caveat: 'The framework is guidance for AI literacy program design and does not validate a specific worker, employer, course, or assessment.',
    claimBoundary: 'Use as workforce and education context only; do not claim DOL endorsement, grant eligibility, or employment-outcome proof.',
    url: 'https://www.dol.gov/agencies/eta/advisories/ten-07-25',
  },
  {
    id: 'dol-ai-worker-wellbeing-best-practices',
    label: 'DOL AI Worker Well-being best practices',
    provider: 'U.S. Department of Labor Office of the Secretary',
    currentVersion: 'AI Best Practices roadmap for developers and employers',
    releaseDate: 'Published October 16, 2024; news-release policy notice reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing employer-facing AI governance, worker-data, human-oversight, transparency, or employment-decision boundary language.',
    usedFor: 'Worker-centered AI governance framing, significant-employment-decision oversight, transparency, worker-data protection, and employment-rights caveats.',
    caveat: 'DOL marks some prior-administration news releases as potentially out of date after January 20, 2025; use this as advisory context only and pair it with current EEOC/ADA/FCRA boundaries.',
    claimBoundary: 'Use as non-binding worker-wellbeing and employer/developer best-practice context only; do not claim DOL endorsement, legal compliance, employment-decision validation, or worker-outcome proof.',
    url: 'https://www.dol.gov/index.php/newsroom/releases/osec/osec20241016',
  },
  {
    id: 'anthropic-economic-index',
    label: 'Anthropic Economic Index',
    provider: 'Anthropic',
    currentVersion: 'March 2026 Learning Curves report plus 2026 Economic Primitives updates',
    releaseDate: 'Published March 24, 2026; prior Economic Index updates retained as context',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review each public Economic Index release and open dataset update before refreshing AI-use claims.',
    usedFor: 'Observed AI use by O*NET task, automation versus augmentation framing, and adoption-inequality caveats.',
    caveat: 'Claude usage is not representative of all AI use, all workers, or all countries, and the source describes observed usage rather than complete automation feasibility.',
    claimBoundary: 'Use as an external AI-use benchmark and caveat layer; do not treat it as the app scoring source until imported task-level datasets are versioned and validated.',
    url: 'https://www.anthropic.com/research/economic-index-march-2026-report',
  },
  {
    id: 'anthropic-economic-index-2026',
    label: 'Anthropic Economic Index January 2026',
    provider: 'Anthropic',
    currentVersion: 'January 2026 Economic Primitives report',
    releaseDate: 'Published January 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review each Economic Index release and before changing automation versus augmentation claims.',
    usedFor: 'Automation versus augmentation framing, observed Claude usage patterns, and country/task-use caveats.',
    caveat: 'Claude usage patterns are observed product usage and are not representative of all AI use, all regions, or labor-market outcomes.',
    claimBoundary: 'Use as observed AI-use context only; do not treat it as direct proof of occupation safety, displacement, or APO accuracy.',
    url: 'https://www.anthropic.com/research/anthropic-economic-index-january-2026-report',
  },
  {
    id: 'anthropic-observed-exposure',
    label: 'Anthropic observed AI exposure research',
    provider: 'Anthropic',
    currentVersion: 'Labor market impacts observed-exposure research',
    releaseDate: '2026 research release',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review when Anthropic publishes new Economic Index labor-market datasets or methodology updates.',
    usedFor: 'Distinguishing theoretical task capability from observed automated, work-related AI use.',
    caveat: 'Observed exposure is based on Claude usage and external task-exposure estimates; it is not a complete labor-market outcome measure.',
    claimBoundary: 'Use to explain why task capability, observed AI use, hiring, and displacement must be separated in commercial reports.',
    url: 'https://www.anthropic.com/research/labor-market-impacts',
  },
  {
    id: 'openai-gdpval',
    label: 'OpenAI GDPval occupational task evaluation',
    provider: 'OpenAI',
    currentVersion: 'GDPval first version',
    releaseDate: 'Published September 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review new GDPval releases and gold-set updates before making capability benchmark claims.',
    usedFor: 'AI capability benchmark framing for economically valuable knowledge-work tasks.',
    caveat: 'GDPval is an evaluation benchmark, not a labor-market forecast, and its first version covers a limited set of knowledge-work occupations.',
    claimBoundary: 'Use for capability trend context only; do not translate benchmark performance directly into job-loss or hiring predictions.',
    url: 'https://arxiv.org/abs/2510.04374',
  },
  {
    id: 'bls-ai-mlr-2025',
    label: 'BLS AI impacts in employment projections',
    provider: 'U.S. Bureau of Labor Statistics Monthly Labor Review',
    currentVersion: '2025 occupational case-study article',
    releaseDate: 'Published February 2025',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review each annual BLS projections cycle and related AI/technology Monthly Labor Review updates.',
    usedFor: 'Claim discipline around AI exposure, employment projections uncertainty, and occupation-specific counterexamples.',
    caveat: 'BLS emphasizes that technology impacts can be gradual and uncertain; exposure does not imply rapid displacement.',
    claimBoundary: 'Use to temper automation claims and explain uncertainty, not as a direct replacement for app scoring or employer-specific forecasts.',
    url: 'https://www.bls.gov/opub/mlr/2025/article/incorporating-ai-impacts-in-bls-employment-projections.htm',
  },
  {
    id: 'wcag-22',
    label: 'WCAG 2.2 accessibility standard',
    provider: 'World Wide Web Consortium',
    currentVersion: 'WCAG 2.2 Recommendation',
    releaseDate: 'December 2024 update',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review when commercial routes are changed and before institutional demos.',
    usedFor: 'Accessibility conformance target for public report, lead-capture, coach, and workforce pilot surfaces.',
    caveat: 'Automated checks cannot prove full WCAG conformance; manual keyboard, screen-reader, contrast, focus, and error-state review are still required.',
    claimBoundary: 'Do not claim WCAG conformance until the audit checklist, remediation evidence, and manual test notes are complete.',
    url: 'https://www.w3.org/TR/WCAG22/',
  },
  {
    id: 'wcag-em-overview',
    label: 'WCAG-EM conformance evaluation overview',
    provider: 'World Wide Web Consortium Web Accessibility Initiative',
    currentVersion: 'WCAG-EM overview with WCAG-EM 2 draft update',
    releaseDate: 'Updated February 5, 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing manual WCAG review scope, sample, evaluator, or procurement-readiness language.',
    usedFor: 'Manual accessibility review scope, representative sample, evaluation reporting, and owner-held WCAG evidence packet methodology.',
    caveat: 'WCAG-EM is evaluation methodology and supporting guidance; it does not itself add WCAG requirements or prove this product conforms.',
    claimBoundary: 'Use as a manual evaluation methodology source only; do not claim WCAG conformance, legal compliance, or procurement approval until the owner-held review evidence is complete and accepted.',
    url: 'https://www.w3.org/WAI/test-evaluate/conformance/wcag-em/',
  },
  {
    id: 'wcag-em-2',
    label: 'WCAG-EM 2.0 digital-product evaluation draft',
    provider: 'World Wide Web Consortium',
    currentVersion: 'W3C Group Note Draft, 05 February 2026',
    releaseDate: 'Published February 5, 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing digital-product sample, complete-process, accessibility-support-baseline, or evaluation-statement requirements.',
    usedFor: 'Digital-product accessibility evaluation framing for app routes, complete processes, sample sets, technologies relied upon, and accessibility-support baseline metadata.',
    caveat: 'WCAG-EM 2.0 is a draft Group Note and is inappropriate to cite as a finalized W3C endorsement or normative requirement.',
    claimBoundary: 'Use as current digital-product evaluation draft context only; do not cite it as a final standard or as evidence of WCAG conformance.',
    url: 'https://www.w3.org/TR/wcag-em-2/',
  },
  {
    id: 'wcag-em-report-tool',
    label: 'WCAG-EM Report Tool',
    provider: 'World Wide Web Consortium Web Accessibility Initiative',
    currentVersion: 'WCAG-EM Report Tool Version 3.0.3',
    releaseDate: 'Updated May 12, 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing manual WCAG review packet report-export or evaluator handoff requirements.',
    usedFor: 'Structured manual WCAG-EM evaluation report generation, owner-held report export, and accessibility evidence packet handoff.',
    caveat: 'The report tool helps structure and export evaluator findings; it does not perform automated checks or independently prove WCAG conformance.',
    claimBoundary: 'Use as a report-generation source only; do not claim WCAG conformance, legal compliance, procurement approval, or completed manual review from tool use alone.',
    url: 'https://www.w3.org/WAI/eval/report-tool/',
  },
  {
    id: 'wcag2ict-22',
    label: 'WCAG2ICT 2.2 non-web ICT guidance',
    provider: 'World Wide Web Consortium',
    currentVersion: 'W3C Group Note, 11 December 2025',
    releaseDate: 'Published December 11, 2025',
    lastVerifiedAt: '2026-06-09',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing downloadable HTML, CSV, report, proof-pack, or non-web artifact accessibility evidence requirements.',
    usedFor: 'Manual review scope for downloaded reports, CSV exports, proof packets, and other non-web information and communications technology artifacts.',
    caveat: 'WCAG2ICT is informative guidance for applying WCAG 2.2 to non-web documents and software; it is not normative and does not itself prove conformance.',
    claimBoundary: 'Use as downloadable-artifact accessibility review guidance only; do not claim WCAG conformance, legal compliance, or procurement approval from referencing it.',
    url: 'https://www.w3.org/TR/wcag2ict-22/',
  },
  {
    id: 'nist-ai-rmf',
    label: 'NIST AI Risk Management Framework',
    provider: 'U.S. National Institute of Standards and Technology',
    currentVersion: 'AI RMF 1.0',
    releaseDate: 'January 2023; current framework reviewed in 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing report governance, review-state, or risk-note language.',
    usedFor: 'Risk notes, human-review states, governance boundaries, and trustworthy AI framing.',
    caveat: 'The AI RMF is a voluntary risk-management framework and does not itself validate a product for employment decisions.',
    claimBoundary: 'Use as a governance scaffold only; do not claim certification, compliance, or formal validation from referencing it.',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
  },
  {
    id: 'nist-ai-genai-profile',
    label: 'NIST AI RMF Generative Artificial Intelligence Profile',
    provider: 'U.S. National Institute of Standards and Technology',
    currentVersion: 'NIST AI 600-1',
    releaseDate: 'July 26, 2024; publication page updated April 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing generative-AI risk notes, human-review controls, or proof-pack governance claims.',
    usedFor: 'Generative-AI-specific risk notes, misuse boundaries, reviewer workflow framing, and AI RMF companion-profile source coverage.',
    caveat: 'The profile is a voluntary companion resource for generative AI risk management and does not certify model quality, safety, employment validity, or legal compliance.',
    claimBoundary: 'Use as current generative-AI risk-management guidance only; do not claim certification, conformance, or product validation from referencing it.',
    url: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence',
  },
  {
    id: 'nist-ssdf',
    label: 'NIST Secure Software Development Framework',
    provider: 'U.S. National Institute of Standards and Technology',
    currentVersion: 'NIST SP 800-218 Version 1.1',
    releaseDate: 'February 2022; current publication page reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing secure-development, release-gate, dependency, or supplier-assurance claims.',
    usedFor: 'Secure-development lifecycle framing, release-gate proof boundaries, vulnerability-reduction language, and supplier-assurance caveats.',
    caveat: 'SSDF is guidance for secure software development practices; source coverage does not prove this repository implements every practice or has supplier attestation.',
    claimBoundary: 'Use as secure-development framework context only; do not claim SSDF conformance, federal attestation, or software-supplier approval from referencing it.',
    url: 'https://csrc.nist.gov/pubs/sp/800/218/final',
  },
  {
    id: 'cisa-secure-by-design',
    label: 'CISA Secure by Design principles',
    provider: 'Cybersecurity and Infrastructure Security Agency',
    currentVersion: 'Shifting the Balance refined Secure by Design principles',
    releaseDate: 'October 2023 refined guidance; current CISA page reviewed June 2026',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing security ownership, transparency, remediation, or launch-gate language.',
    usedFor: 'Secure-by-design ownership, transparency, leadership-accountability, and buyer-facing security proof boundaries.',
    caveat: 'The CISA principles are a product-security direction and do not prove secure defaults, vulnerability elimination, customer-security outcomes, or compliance for this app.',
    claimBoundary: 'Use to frame security posture and unresolved proof gates only; do not claim Secure by Design pledge status, certification, or production hardening without separate evidence.',
    url: 'https://www.cisa.gov/news-events/news/applying-secure-design-thinking-events-news',
  },
  {
    id: 'owasp-asvs-5',
    label: 'OWASP Application Security Verification Standard',
    provider: 'OWASP Foundation',
    currentVersion: 'ASVS 5.0.0',
    releaseDate: 'Released May 30, 2025',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing application-security gate scope, proof-pack security claims, or procurement-facing assurance language.',
    usedFor: 'Web-application security verification framing, procurement-oriented assurance language, and ASVS-versioned proof-boundary caveats.',
    caveat: 'ASVS source coverage does not mean the application has been independently tested against ASVS or satisfies any ASVS level.',
    claimBoundary: 'Use as application-security verification reference only; do not claim ASVS Level 1, 2, or 3 status without a scoped ASVS assessment and evidence report.',
    url: 'https://owasp.org/www-project-application-security-verification-standard/',
  },
  {
    id: 'owasp-llm-top-10-2025',
    label: 'OWASP Top 10 for LLM Applications 2025',
    provider: 'OWASP GenAI Security Project',
    currentVersion: '2025 Top 10 for LLM Applications',
    releaseDate: 'November 17, 2024',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing LLM prompt, output-handling, retrieval, agentic, or AI proof-pack risk language.',
    usedFor: 'LLM-specific security risk framing for prompt injection, output handling, sensitive information disclosure, supply chain, and overreliance boundaries.',
    caveat: 'The Top 10 is risk guidance and does not prove this app is protected against each LLM vulnerability class.',
    claimBoundary: 'Use as LLM risk taxonomy only; do not claim OWASP GenAI security conformance, red-team coverage, or secure AI deployment without separate test evidence.',
    url: 'https://genai.owasp.org/resource/owasp-top-10-for-llm-applications-2025/',
  },
  {
    id: 'pci-dss-v4-0-1',
    label: 'PCI DSS v4.0.1 publication notice',
    provider: 'PCI Security Standards Council',
    currentVersion: 'PCI DSS v4.0.1',
    releaseDate: 'Published June 11, 2024; v4.0 retired December 31, 2024',
    lastVerifiedAt: '2026-06-08',
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing payment, checkout, card-data, or live-revenue proof boundaries.',
    usedFor: 'Payment-data security framing, Stripe proof boundary language, owner-held payment evidence caveats, and buyer security-review context.',
    caveat: 'Using Stripe Checkout and referencing PCI DSS guidance does not prove PCI DSS scope, assessment status, merchant compliance, or card-data environment controls.',
    claimBoundary: 'Use as payment security context only; do not claim PCI DSS compliance, SAQ completion, ROC/AOC status, or cardholder-data environment validation without separate owner-held assessment evidence.',
    url: 'https://blog.pcisecuritystandards.org/just-published-pci-dss-v4-0-1',
  },
  {
    id: 'owasp-file-upload',
    label: 'OWASP File Upload Cheat Sheet',
    provider: 'OWASP Cheat Sheet Series',
    currentVersion: 'Current public file-upload guidance',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing resume upload, file validation, parser, or storage behavior.',
    usedFor: 'Resume upload boundary controls: extension allowlist, content-type caveat, file-signature checks, size limits, storage minimization, and malware-scan caveats.',
    caveat: 'OWASP guidance informs secure upload handling, but it does not prove any uploaded file is safe, malware-free, or parsed completely.',
    claimBoundary: 'Do not enable paid PDF/DOCX upload workflows until server-side validation, parser behavior, deletion receipts, and unresolved malware-scan limitations are visible in the proof packet.',
    url: 'https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html',
  },
  {
    id: 'cwe-59-link-following',
    label: 'CWE-59 link-following weakness',
    provider: 'MITRE Common Weakness Enumeration',
    currentVersion: 'CWE-59: Improper Link Resolution Before File Access',
    releaseDate: 'Current CWE entry reviewed June 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing owner-held proof hashing, uploaded-file handling, archive extraction, or filesystem path validation.',
    usedFor: 'Owner proof-artifact hashing boundary for rejecting symbolic links, hard-linked files, and path-confused proof inputs before storing redacted hash metadata.',
    caveat: 'CWE-59 is a weakness taxonomy and does not prove the app is immune to every filesystem race, archive extraction, upload, or storage-path attack.',
    claimBoundary: 'Use as link-following and hard-link risk context only; do not claim secure file-processing certification without scoped security testing and owner-held evidence-flow review.',
    url: 'https://cwe.mitre.org/data/definitions/59.html',
  },
  {
    id: 'cwe-367-toctou',
    label: 'CWE-367 TOCTOU race-condition weakness',
    provider: 'MITRE Common Weakness Enumeration',
    currentVersion: 'CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition',
    releaseDate: 'Current CWE entry reviewed June 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing owner-held proof hashing, uploaded-file handling, archive extraction, or filesystem path validation.',
    usedFor: 'Owner proof-artifact hashing boundary for validating opened file descriptors and avoiding filename check/use gaps before storing redacted hash metadata.',
    caveat: 'CWE-367 is a weakness taxonomy and does not prove the app is immune to every filesystem race, concurrent write, archive extraction, upload, or storage-path attack.',
    claimBoundary: 'Use as TOCTOU and file-identity race context only; do not claim secure file-processing certification without scoped security testing and owner-held evidence-flow review.',
    url: 'https://cwe.mitre.org/data/definitions/367.html',
  },
  {
    id: 'supabase-edge-functions',
    label: 'Supabase Edge Functions',
    provider: 'Supabase',
    currentVersion: 'Current Edge Functions platform documentation',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing Edge Function parser, upload, runtime-limit, or deployment assumptions.',
    usedFor: 'Server-side parser boundary, multipart upload handling, runtime limits, auth/header validation, and deployment runbook caveats.',
    caveat: 'Edge Functions are suitable for short validation and orchestration; heavy parsing, antivirus scanning, or large-file processing may need a dedicated service or background worker.',
    claimBoundary: 'Do not claim production PDF/DOCX parser readiness until the deployed function, file-size limits, parser adapter, deletion proof, and error-path artifacts pass verification.',
    url: 'https://supabase.com/docs/guides/functions',
  },
  {
    id: 'ada-ai-hiring-guidance',
    label: 'ADA algorithmic hiring guidance',
    provider: 'U.S. Department of Justice and EEOC',
    currentVersion: 'Algorithms, Artificial Intelligence, and Disability Discrimination in Hiring guidance',
    releaseDate: 'Guidance current as of 2026 review',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before any employer-facing workflow could influence selection, promotion, or workforce decisions.',
    usedFor: 'Employment-decision disclaimers, accommodation language, and human-review guardrails.',
    caveat: 'This guidance is not a substitute for legal advice and does not make the product validated for selection procedures.',
    claimBoundary: 'Use reports for planning and discussion only unless a formal validation, accommodation, and adverse-impact review program exists.',
    url: 'https://www.ada.gov/resources/ai-guidance/',
  },
  {
    id: 'eeoc-employment-selection-procedures',
    label: 'EEOC employment tests and selection procedures',
    provider: 'U.S. Equal Employment Opportunity Commission',
    currentVersion: 'Employment Tests and Selection Procedures technical assistance',
    releaseDate: 'December 1, 2007; current page reviewed in 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before any employer-facing workflow could influence selection, promotion, or workforce decisions.',
    usedFor: 'Employment-selection overclaim boundaries, adverse-impact caveats, and proof that report outputs are planning artifacts unless formally validated.',
    caveat: 'This technical assistance is not legal advice and does not validate this product as an employment selection procedure.',
    claimBoundary: 'Do not use proof-pack scores for hiring, firing, promotion, compensation, retention, screening, or eligibility decisions without a formal validated employment-selection program.',
    url: 'https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures',
  },
  {
    id: 'cfpb-employment-algorithmic-scores',
    label: 'CFPB employment algorithmic score circular',
    provider: 'Consumer Financial Protection Bureau',
    currentVersion: 'Consumer Financial Protection Circular 2024-06',
    releaseDate: 'October 24, 2024; Federal Register publication November 12, 2024',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before any report, score, or worker dossier is shared with an employer or third party.',
    usedFor: 'Consumer-report and employment-purpose overclaim boundaries for individual resume and worker-score artifacts.',
    caveat: 'This circular does not make the product a consumer reporting agency by itself, but it flags FCRA risk if third-party reports or scores are used for employment purposes.',
    claimBoundary: 'Do not furnish individual proof-pack reports to employers for employment purposes unless FCRA, notice, dispute, permission, accuracy, and legal review controls are implemented.',
    url: 'https://www.consumerfinance.gov/compliance/circulars/consumer-financial-protection-circular-2024-06-background-dossiers-and-algorithmic-scores-for-hiring-promotion-and-other-employment-decisions/',
  },
  {
    id: 'eu-ai-act-annex-iii-high-risk',
    label: 'EU AI Act Annex III high-risk AI systems',
    provider: 'European Commission AI Act Service Desk',
    currentVersion: 'Regulation (EU) 2024/1689 Annex III',
    releaseDate: 'Official version of 13 June 2024; in force 1 August 2024',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'high',
    refreshCadence: 'Review before changing EU-facing, employer-facing, worker-management, candidate-evaluation, education, vocational-training, or self-employment access boundary language.',
    usedFor: 'International high-risk AI boundary for employment, worker management, self-employment access, education, and vocational-training use cases.',
    caveat: 'Annex III classification depends on intended purpose, deployment context, and EU legal analysis; this source does not make the product compliant or non-high-risk by itself.',
    claimBoundary: 'Use proof packs as planning and coaching artifacts only; do not market them for EU recruitment, candidate filtering, worker monitoring, work-relationship decisions, education admission, or access-to-self-employment decisions without a separate AI Act classification and compliance program.',
    url: 'https://ai-act-service-desk.ec.europa.eu/en/ai-act/annex-3',
  },
  {
    id: 'iso-42001',
    label: 'ISO/IEC 42001 AI management system',
    provider: 'International Organization for Standardization',
    currentVersion: 'ISO/IEC 42001:2023',
    releaseDate: 'Published December 2023',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'active',
    confidence: 'medium',
    refreshCadence: 'Review before changing AI governance, review attestation, or buyer trust claims.',
    usedFor: 'AI governance, traceability, transparency, and review-attestation framing for institutional proof-pack delivery.',
    caveat: 'Referencing ISO/IEC 42001 does not certify this product or any customer AI management system.',
    claimBoundary: 'Use as governance design context only; do not claim ISO certification or compliance from source labeling alone.',
    url: 'https://www.iso.org/standard/42001',
  },
  {
    id: 'esco',
    label: 'ESCO skills and occupation taxonomy',
    provider: 'European Commission',
    currentVersion: 'ESCO v1.2.1',
    releaseDate: 'Last update 2025-12-10',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Monitor ESCO release notes before international skill mapping claims.',
    usedFor: 'International skill language, multilingual skills, and non-U.S. occupation alignment.',
    caveat: 'Requires mapping to local SOC/O*NET rows before it can power scored U.S. reports.',
    claimBoundary: 'Adapter boundary only until the ESCO import, crosswalk, and validation checks exist in this repo.',
    url: 'https://esco.ec.europa.eu/en/use-esco/use-esco-services-api',
  },
  {
    id: 'abs-osca-2024',
    label: 'Occupation Standard Classification for Australia 2024',
    provider: 'Australian Bureau of Statistics',
    currentVersion: 'OSCA 2024',
    releaseDate: 'Released December 2024; replacement status reviewed June 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'high',
    refreshCadence: 'Review when ABS publishes OSCA updates and when JSA migrates occupation profiles from ANZSCO.',
    usedFor: 'Forward Australian occupation-classification boundary and ANZSCO-to-OSCA transition notes.',
    caveat: 'OSCA replaces ANZSCO in Australia, but many public labor-market tables may still publish ANZSCO-aligned values during transition.',
    claimBoundary: 'Use OSCA as the forward Australian classification boundary; do not display local Australian values unless the source table, classification basis, and suppression notes match.',
    url: 'https://www.abs.gov.au/about/key-priorities/about-osca/osca-2024',
  },
  {
    id: 'lightcast',
    label: 'Lightcast skills and labor-market data',
    provider: 'Lightcast',
    currentVersion: 'Commercial adapter boundary',
    releaseDate: 'Not licensed in this repository',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Review only after commercial data agreement and adapter credentials exist.',
    usedFor: 'Job-posting demand, emerging skills, and employer language once licensed.',
    caveat: 'Not bundled in this repository; production use requires a licensed data agreement and ingestion adapter.',
    claimBoundary: 'Do not imply Lightcast-backed scoring until a licensed adapter and provenance log are implemented.',
    url: 'https://lightcast.io/',
  },
  {
    id: 'workera-positioning',
    label: 'Workera skills intelligence positioning',
    provider: 'Workera',
    currentVersion: 'Public product overview',
    releaseDate: 'Reviewed May 2026',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Review during competitive-positioning refreshes before changing skills-intelligence claims.',
    usedFor: 'Competitive landscape context around verified skills, defensible evidence, and enterprise buyer expectations.',
    caveat: 'Public competitor positioning is not a data feed, benchmark, or endorsement.',
    claimBoundary: 'Use only for market-positioning context; do not imply Workera-backed validation, integration, or comparable assessment depth.',
    url: 'https://www.workera.ai/product-overview',
  },
  {
    id: 'serpapi',
    label: 'Live market search signals',
    provider: 'SerpAPI-compatible search adapter',
    currentVersion: 'Adapter boundary',
    releaseDate: 'Runtime query timestamp required',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'adapter-ready',
    confidence: 'medium',
    refreshCadence: 'Per-query timestamp, cache key, and jurisdiction capture required.',
    usedFor: 'Current SERP/job-market snapshots for outreach and content validation.',
    caveat: 'Search results are volatile and must be cached with query, timestamp, and jurisdiction.',
    claimBoundary: 'Use only as freshness context until a query log, cache policy, and result-review workflow are implemented.',
    url: 'https://serpapi.com/',
  },
  {
    id: 'llm-output',
    label: 'LLM-generated analysis',
    provider: 'Configured AI model or Supabase Edge Function',
    currentVersion: 'Runtime configured model',
    releaseDate: 'Runtime model/version metadata required',
    lastVerifiedAt: SOURCE_MANIFEST_LAST_VERIFIED_AT,
    integrationStatus: 'llm-output',
    confidence: 'low',
    refreshCadence: 'Capture model name, prompt version, and generation timestamp per artifact.',
    usedFor: 'Narrative explanations, resume rewrites, caveat summaries, and draft recommendations.',
    caveat: 'LLM output is advisory. It needs source grounding, human review, and should never be the sole basis for employment decisions.',
    claimBoundary: 'Treat as draft narrative unless grounded source IDs, human review state, and prompt/model metadata are attached.',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
  },
];

export function getSourceManifestSnapshot(): Record<string, SourceManifestSnapshotEntry> {
  return SOURCE_REFRESH_MANIFEST.reduce<Record<string, SourceManifestSnapshotEntry>>((acc, source) => {
    acc[source.id] = {
      label: source.label,
      provider: source.provider,
      currentVersion: source.currentVersion,
      releaseDate: source.releaseDate,
      lastVerifiedAt: source.lastVerifiedAt,
      integrationStatus: source.integrationStatus,
      confidence: source.confidence,
    };
    return acc;
  }, {});
}

export function getActiveSourceVersionSummary(): string {
  return SOURCE_REFRESH_MANIFEST.filter((source) => source.integrationStatus === 'active')
    .map((source) => `${source.label}: ${source.currentVersion} (${source.releaseDate})`)
    .join('; ');
}
