import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Download, Mail, CheckCircle2, Loader2 } from 'lucide-react';
import { trackEvent } from '@/lib/posthog';
import type { OccupationRiskData } from '@/data/occupationRiskData';

interface SEOReportDownloadProps {
  data: OccupationRiskData;
  occupationSlug: string;
}

function generateReportHTML(data: OccupationRiskData): string {
  const riskLevel = data.overallRisk <= 30 ? 'Low' : data.overallRisk <= 60 ? 'Medium' : 'High';
  const riskColor = data.overallRisk <= 30 ? '#10b981' : data.overallRisk <= 60 ? '#f59e0b' : '#ef4444';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>AI Automation Risk Report: ${data.title} | Automation Insights</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1e293b; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 28px; margin-bottom: 8px; }
    h2 { font-size: 20px; margin: 32px 0 16px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
    .header { text-align: center; margin-bottom: 40px; padding-bottom: 24px; border-bottom: 3px solid ${riskColor}; }
    .header .subtitle { color: #64748b; font-size: 14px; margin-top: 4px; }
    .score-box { background: #f8fafc; border: 2px solid ${riskColor}; border-radius: 12px; padding: 24px; text-align: center; margin: 24px 0; }
    .score-value { font-size: 48px; font-weight: 800; color: ${riskColor}; }
    .score-label { color: #64748b; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; }
    .badge { display: inline-block; background: ${riskColor}; color: white; padding: 4px 16px; border-radius: 20px; font-weight: 600; font-size: 14px; margin-top: 8px; }
    .stats { display: flex; gap: 16px; margin: 24px 0; }
    .stat { flex: 1; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center; }
    .stat-value { font-size: 20px; font-weight: 700; color: #0f172a; }
    .stat-label { font-size: 12px; color: #64748b; margin-top: 4px; }
    .task-list { list-style: none; padding: 0; }
    .task-list li { padding: 10px 16px; margin: 6px 0; border-radius: 8px; font-size: 14px; }
    .task-risk { background: #fef2f2; border-left: 4px solid #ef4444; }
    .task-safe { background: #f0fdf4; border-left: 4px solid #10b981; }
    .task-reskill { background: #eff6ff; border-left: 4px solid #3b82f6; }
    .bridge { background: #f0fdf4; border: 2px solid #10b981; border-radius: 12px; padding: 20px; margin: 16px 0; }
    .bridge-title { font-weight: 700; color: #10b981; margin-bottom: 4px; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 12px; }
    .footer a { color: #2dd4a8; text-decoration: none; }
    @media print { body { padding: 20px; } .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>AI Automation Risk Report</h1>
    <div class="subtitle">${data.title} (SOC: ${data.code})</div>
    <div class="subtitle">Generated by Automation Insights &bull; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </div>

  <div class="score-box">
    <div class="score-label">Overall Automation Risk</div>
    <div class="score-value">${data.overallRisk}%</div>
    <div class="badge">${riskLevel} Risk</div>
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-value">${data.averageSalary}</div>
      <div class="stat-label">Average Salary</div>
    </div>
    <div class="stat">
      <div class="stat-value">${data.jobGrowth}</div>
      <div class="stat-label">Job Growth (10yr)</div>
    </div>
    <div class="stat">
      <div class="stat-value">${data.industry}</div>
      <div class="stat-label">Industry</div>
    </div>
  </div>

  <h2>Tasks at Highest Automation Risk</h2>
  <ul class="task-list">
    ${data.highRiskTasks.map(t => `<li class="task-risk">${t}</li>`).join('\n    ')}
  </ul>

  <h2>Skills That Remain Human</h2>
  <ul class="task-list">
    ${data.safeSkills.map(s => `<li class="task-safe">${s}</li>`).join('\n    ')}
  </ul>

  <h2>Recommended Reskilling Paths</h2>
  <ul class="task-list">
    ${data.reskillingSuggestions.map(r => `<li class="task-reskill">${r}</li>`).join('\n    ')}
  </ul>

  <h2>Bridge Role Recommendation</h2>
  <div class="bridge">
    <div class="bridge-title">${data.bridgeRole}</div>
    <div>Automation Risk: ${data.bridgeRoleRisk}% &mdash; ${data.bridgeRoleRisk <= 30 ? 'Significantly safer' : 'Lower risk'} than ${data.title}</div>
  </div>

  <div class="footer">
    <p>Data sourced from O*NET 29.3 (U.S. Department of Labor) and WEF Future of Jobs 2025</p>
    <p style="margin-top: 8px;">Get your full personalized analysis at <a href="https://automationinsights.app">automationinsights.app</a></p>
    <p style="margin-top: 4px;">For career coaches: white-label this report &mdash; <a href="https://automationinsights.app/for-coaches">Learn about Coach Pro</a></p>
  </div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;
}

export function SEOReportDownload({ data, occupationSlug }: SEOReportDownloadProps) {
  const [email, setEmail] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim()) return;

    setLoading(true);

    // Track the lead capture event
    trackEvent('seo_pdf_lead_captured', {
      email: email.trim(),
      occupation: data.title,
      occupation_slug: occupationSlug,
      risk_score: data.overallRisk,
    });

    // Store in localStorage for backup
    try {
      const leads = JSON.parse(localStorage.getItem('email_leads') || '[]');
      leads.push({ email: email.trim(), occupation: occupationSlug, timestamp: new Date().toISOString() });
      localStorage.setItem('email_leads', JSON.stringify(leads));
    } catch {}

    setSubmitted(true);
    setLoading(false);

    // Generate and open the PDF report
    const html = generateReportHTML(data);
    const reportWindow = window.open('', '_blank');
    if (reportWindow) {
      reportWindow.document.open('text/html');
      reportWindow.document.write(html);
      reportWindow.document.close();
    }
  };

  if (submitted) {
    return (
      <Card className="border-emerald-500/30 bg-emerald-500/5">
        <CardContent className="p-6 text-center">
          <CheckCircle2 className="h-10 w-10 text-emerald-500 mx-auto mb-3" />
          <h3 className="text-lg font-bold mb-1">Report Downloaded!</h3>
          <p className="text-sm text-muted-foreground mb-4">
            Check your new browser tab. Use File → Save as PDF or Print → Save as PDF.
          </p>
          <Button
            variant="outline"
            onClick={() => {
              const html = generateReportHTML(data);
              const reportWindow = window.open('', '_blank');
              if (reportWindow) {
                reportWindow.document.open('text/html');
                reportWindow.document.write(html);
                reportWindow.document.close();
              }
            }}
          >
            <Download className="h-4 w-4 mr-2" />
            Download Again
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-[var(--accent-primary)]/30 bg-[var(--accent-primary)]/5">
      <CardHeader className="text-center pb-3">
        <CardTitle className="text-xl flex items-center justify-center gap-2">
          <Download className="h-5 w-5" />
          Download Full Report as PDF
        </CardTitle>
        <CardDescription>
          Get a printable, shareable AI risk report for {data.title}s — free.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              type="email"
              required
              placeholder="your@email.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="pl-10"
            />
          </div>
          <Button type="submit" disabled={loading} className="whitespace-nowrap">
            {loading ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <Download className="h-4 w-4 mr-2" />
            )}
            Download PDF
          </Button>
        </form>
        <p className="text-xs text-muted-foreground text-center mt-3">
          No spam. We'll send career insights based on your occupation interest.
        </p>
      </CardContent>
    </Card>
  );
}
