// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type RuntimeEnv = Record<string, string | undefined>;
type RuntimeWindow = Window & {
  __CAIE_ENV?: RuntimeEnv;
  __ENV?: RuntimeEnv;
  ENV?: RuntimeEnv;
  env?: RuntimeEnv;
};
type RuntimeGlobal = typeof globalThis & {
  __CAIE_ENV?: RuntimeEnv;
};

// Resolve environment variables from multiple compatible sources (Vite, Node, global runtime)
const importMetaEnv = (import.meta as ImportMeta & { env?: RuntimeEnv }).env;
const envSources: RuntimeEnv[] = [];

// When bundled by Vite, import.meta.env is replaced statically. Capture it first.
if (importMetaEnv) {
  envSources.push(importMetaEnv);
}

const processEnv = typeof process !== 'undefined' ? (process.env as Record<string, string | undefined>) : undefined;
if (processEnv) envSources.push(processEnv);

const runtimeGlobal = globalThis as RuntimeGlobal;
const globalEnv = typeof globalThis !== 'undefined' ? runtimeGlobal.__CAIE_ENV : undefined;
if (globalEnv) envSources.push(globalEnv);

const runtimeWindow = typeof window !== 'undefined' ? (window as RuntimeWindow) : undefined;
const windowEnv = runtimeWindow
  ? runtimeWindow.__CAIE_ENV || runtimeWindow.__ENV || runtimeWindow.ENV || runtimeWindow.env
  : undefined;
if (windowEnv) envSources.push(windowEnv);

const resolveEnvVar = (...keys: string[]): string | undefined => {
  for (const source of envSources) {
    if (!source) continue;
    for (const key of keys) {
      const value = source[key];
      if (typeof value === 'string' && value.trim().length > 0) {
        return value.trim();
      }
    }
  }
  return undefined;
};

// Prefer Vite-prefixed vars but support common alternatives used in hosting platforms
const SUPABASE_URL = resolveEnvVar('VITE_SUPABASE_URL', 'PUBLIC_SUPABASE_URL', 'SUPABASE_URL');
const SUPABASE_PUBLISHABLE_KEY = resolveEnvVar('VITE_SUPABASE_ANON_KEY', 'PUBLIC_SUPABASE_ANON_KEY', 'SUPABASE_ANON_KEY');
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.warn(
    'Supabase environment variables are missing. Public pages will render, but Supabase-backed actions will fail gracefully until VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are configured.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://supabase-disabled.invalid',
  SUPABASE_PUBLISHABLE_KEY || 'supabase-disabled-anon-key',
  {
    auth: {
      persistSession: isSupabaseConfigured,
      autoRefreshToken: isSupabaseConfigured,
      detectSessionInUrl: isSupabaseConfigured,
    },
  }
);
